### ISSUE TITLE
OSPFv3 sessions wrongly reported as up

### ISSUE THREAD

**Issue by mweinelt** [czerwonk/bird_exporter#2]
A disabled protocol is wrongly reported as up.

```
protocol ospf o_hrz {
	disabled;
	table t_hrz;
	import all;
	export none;
	area 0 {
		interface "eth0" {
			hello 10;
		};
	};
};
```

```sh
# birdc6 s p | grep "^o_hrz"
o_hrz    OSPF     t_hrz    down   1494926414
```

```sh
# curl -s localhost:9200/metrics | grep o_hrz 
ospfv3_up{name="o_hrz"} 1
ospfv3_prefix_count_import{name="o_hrz"} 0
ospfv3_prefix_count_export{name="o_hrz"} 0
ospfv3_uptime{name="o_hrz"} 9090
```

**Comment by prauscher** [comment]
The problem seems to be in [line 87 of parser.go](https://github.com/czerwonk/bird_exporter/blob/master/parser.go#L87):
```
	if proto == OSPF || state == "Established" {
		return 1
```
so, all OSPF protocols are up all the time. One would need to also transmit match[4] from parseLineForProtocol (line 51) to check if it is "down" or not (other values might be "start" or "up").
